### ISSUE TITLE
what does this python code mean

### ISSUE THREAD

**Issue by divenal** [hoggyhoggy/givenergy-modbus-async#27]
https://github.com/hoggyhoggy/givenergy-modbus-async/blob/50d72dd3914777f633517b1b3c3541326ed679dd/givenergy_modbus/pdu/write_registers.py#L114

I don't understand this expression - seems to me it can never fire ?

https://stackoverflow.com/questions/43271850/confusion-about-x-y-z-in-python

so it's equivalent to     `if 0 > value and value > 0xffff:`  which is surely impossible. I can't get this exception to go off, anyway.

**Comment by hoggyhoggy** [comment]
The only possible relevance I can think of is a what also caught out the Giv App early on, negative temperatures from the battery pack in freezing temps resulting in it reporting temperatures of the sun? Still don't think it would fire though?
